## Two functions makeCacheMatrix and cacheSolve that allow enable the caching of the 
## results of a matrix inversion.

# Example:
# m <- makeCacheMatrix()
# m$setMatrix(matrix(c(1,0,0,0,2,0,0,0,3),3,3))
# cacheSolve(m) # Will estimate the inverse of m
# cacheSolve(m) # Will retrieve the cached value of inverse of m

## makeCacheMatrix ##
# Creates a list object of four functions that can store a matrix and cache it's inverse
# to save time on repeated calculations.
# 4 functions are:
#   1 - setMatrix(<matrix>) - stores a matrix and sets the cached inverse to NULL
# 	2 - getMatrix() - retrieves the stored matrix
# 	3 - setInverse() - stores the inverse matrix
#   4 - getInverse() - retrieves the inverse matrix

makeCacheMatrix <- function(x = matrix()) 
{
	inv_x <- NULL
	
	setMatrix <- function(y)
	{
		# Assign the input argument of setMatrix (y) to the 
		# variable x in different environment.
		x <<- y 
		
		# Assuming that if setMatrix has been called, then
		# matrix x has changed and cached matrix inverse is
		# now invalid so set to NULL.		
		inv_x <<- NULL 
	}
	
	getMatrix <- function() 
	{
		x # Returns x which is defined in the enviroment of setMatrix.
	}
	
	setInverse <- function(inverseMatrix) 
	{
		# Assign the input argument of setInverse (inverseMatrix) to the 
		# variable inv_x in a different environment.
		inv_x <<- inverseMatrix
	}
	getInverse <- function() 
	{
		inv_x # Returns inv_x which is defined in the enviroment of setMatrix.
	} 
	
	# Output list 
	list(getMatrix = getMatrix, setMatrix = setMatrix,
	 	 getInverse = getInverse, setInverse = setInverse)
}

## cacheSolve ##
# Function that takes as an input the list object generated by makeCacheMatrix
# cacheSolve either calculates the inverse of the matrix  using SOLVE 
# or retrieves the cached inverse from a previous call.

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
        if (is.null(x$getInverse()))
        {
        	print("Estimating new inverse")
        	inverseMatrix <- solve(x$getMatrix())
        	x$setInverse(inverseMatrix)
        } else
        {
        	print("Retrieving cached inverse")
        	inverseMatrix <-x$getInverse()
        }
        inverseMatrix
}
